language: python
python: 3.7
dist: xenial
sudo: false

branches:
  only:
    - master

install:
  - pip install -r requirements.txt

before_install:
  - export DEBUG=True

script:
  - black musr_project/ --check
  - python musr_project/manage.py test musr
